# Translations template for nova_powervm.
# Copyright (C) 2016 IBM Corp.
# This file is distributed under the same license as the nova_powervm
# project.
# Automatically generated, 2016.
#
msgid ""
msgstr ""
"Project-Id-Version: nova_powervm 2.0.0\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-04-14 03:14-0400\n"
"PO-Revision-Date: 2016-04-14 03:14-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.3.2\n"

#: nova_powervm/virt/powervm/driver.py:1471
msgid "Live migration timed out. Aborting migration"
msgstr "Истек тайм-аут оперативной миграции. Миграция прервана"

#: nova_powervm/virt/powervm/live_migration.py:324
msgid "Live migration failed."
msgstr "Сбой оперативной миграции."

#: nova_powervm/virt/powervm/live_migration.py:374
#, python-format
msgid "Migration recover failed with error: %s"
msgstr "Не удалось восстановить миграцию. Ошибка: %s"

#: nova_powervm/virt/powervm/live_migration.py:402
msgid ""
"Abort of live migration has failed. This is non-blocking. Exception is "
"logged below."
msgstr ""
"Сбой прерывания оперативной миграции. Это неблокирующая ситуация. Исключительная ситуация "
"описана ниже."

#: nova_powervm/virt/powervm/vif.py:195
#, python-format
msgid "Unable to unplug VIF with mac %(mac)s for instance %(inst)s."
msgstr "Не удалось отсоединить VIF с mac %(mac)s для экземпляра %(inst)s."

#: nova_powervm/virt/powervm/vm.py:628
#, python-format
msgid "Virtual machine delete failed: LPARID=%s"
msgstr "Сбой удаления виртуальной машины: LPARID=%s"

#: nova_powervm/virt/powervm/disk/localdisk.py:262
#, python-format
msgid "Disk %s not found during resize."
msgstr "В процессе изменения размера не найден диск %s."

#: nova_powervm/virt/powervm/disk/ssp.py:371
#, python-format
msgid "Removing failed LU %s."
msgstr "Удаление сбойного LU %s."

#: nova_powervm/virt/powervm/disk/ssp.py:471
#, python-format
msgid "Error checking for shared storage. exception=%s"
msgstr "Ошибка проверки общей памяти. Исключительная ситуация=%s"

#: nova_powervm/virt/powervm/nvram/manager.py:109
#: nova_powervm/virt/powervm/nvram/manager.py:172
#, python-format
msgid "Could not update NVRAM: %s"
msgstr "Не удалось обновить NVRAM: %s"

#: nova_powervm/virt/powervm/tasks/network.py:73
#, python-format
msgid ""
"Unable to remove VIFs from instance %(inst)s because the system is not in"
" a correct state.  The reason reported by the system is: %(reason)s"
msgstr ""
"Не удалось удалить VIF из экземпляра %(inst)s, так как система находится в"
" неправильном состоянии. Причина, указанная системой: %(reason)s"

#: nova_powervm/virt/powervm/tasks/network.py:139
#, python-format
msgid ""
"Unable to create VIF(s) for instance %(sys)s.  The VM was in a state "
"where VIF plugging is not acceptable.  The reason from the system is: "
"%(reason)s"
msgstr ""
"Не удалось создать VIF для экземпляра %(sys)s.  ВМ находится в состоянии, "
"в котором подсоединение VIF не поддерживается. Причина, указанная системой: "
"%(reason)s"

#: nova_powervm/virt/powervm/tasks/network.py:162
#, python-format
msgid "Error waiting for VIF to be created for instance %(sys)s"
msgstr "Ошибка при ожидании создания VIF для экземпляра %(sys)s"

#: nova_powervm/virt/powervm/tasks/network.py:171
#, python-format
msgid "VIF Plug failure for callback on event %(event)s for instance %(uuid)s"
msgstr "Сбой подключения VIF для обратного вызова по событию %(event)s для экземпляра %(uuid)s"

#: nova_powervm/virt/powervm/tasks/vm.py:102
#, python-format
msgid "Unable to fetch NVRAM for instance %(name)s. Exception: %(reason)s"
msgstr "Не удалось получить NVRAM для экземпляра %(name)s. Исключительная ситуация: %(reason)s"

#: nova_powervm/virt/powervm/tasks/vm.py:271
#, python-format
msgid "Unable to store NVRAM for instance %(name)s. Exception: %(reason)s"
msgstr "Не удалось сохранить NVRAM для экземпляра %(name)s. Исключительная ситуация: %(reason)s"

#: nova_powervm/virt/powervm/tasks/vm.py:301
#, python-format
msgid "Unable to delete NVRAM for instance %(name)s. Exception: %(reason)s"
msgstr "Не удалось удалить NVRAM для экземпляра %(name)s. Исключительная ситуация: %(reason)s"

#: nova_powervm/virt/powervm/volume/npiv.py:408
#, python-format
msgid "Mappings were not able to find a proper VIOS. The port mappings were %s."
msgstr "Не удалось найти подходящий VIOS по связям. Связи порта: %s."

#: nova_powervm/virt/powervm/volume/vscsi.py:393
#, python-format
msgid "Cannot detach volumes from virtual machine: %s"
msgstr "Не удалось отключить тома от виртуальной машины: %s"

#: nova_powervm/virt/powervm/volume/vscsi.py:395
#, python-format
msgid "Error: %s"
msgstr "Ошибка: %s"


# ENGL1SH_VERS10N 63189_5 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 44
# T9N_SH1P_STR1NG PV131AAP001 3
